version: '3.8'

services:
  rust-battlemetrics-bot:
    container_name: rust-battlemetrics-bot
    image: negrii/rust-battlemetrics-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 300

volumes:
  mariadb_data: